// Regenerates src/blocks/icon/icons.ts from Phosphor's "regular" weight (MIT).
// Usage: node scripts/icons.mjs <path to node_modules/@phosphor-icons/react>
// The renderer ships only this curated list (≤ 200 icons); the names go into
// the block manifest so the editor and the AI can pick them.
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const NAMES = `
arrow-right arrow-left arrow-up arrow-down arrow-up-right arrow-square-out caret-right caret-left caret-down caret-up
check check-circle x x-circle plus minus list magnifying-glass house user users user-circle
shopping-cart shopping-bag storefront tag gift credit-card wallet truck package receipt currency-dollar percent
star heart thumbs-up smiley chat-circle chats envelope envelope-simple phone map-pin map-trifold globe
calendar calendar-check clock timer bell bookmark book-open newspaper article file-text pencil pen-nib
paint-brush palette camera image images video-camera play play-circle pause music-note microphone headphones
monitor laptop device-mobile desktop cloud cloud-arrow-up database code terminal-window gear wrench hammer
shield-check lock lock-open key eye lightning rocket target trophy medal chart-bar chart-line chart-pie trend-up
presentation-chart briefcase buildings building-office factory handshake lightbulb puzzle-piece sparkle sun moon
leaf plant tree flower drop fire coffee wine fork-knife cooking-pot pizza hamburger car airplane bicycle boat train
compass mountains umbrella first-aid heartbeat pill stethoscope barbell person-simple-run baby dog paw-print
graduation-cap student chalkboard-teacher books scissors t-shirt dress diamond crown info question warning
warning-circle seal-check certificate link link-simple share-network download-simple upload-simple paper-plane-tilt
copy trash funnel sliders dots-three list-checks check-square quotes hash at
rows columns browsers squares-four arrows-vertical text-h text-t cursor-click app-window sidebar-simple cards slideshow
instagram-logo facebook-logo x-logo linkedin-logo youtube-logo tiktok-logo whatsapp-logo github-logo pinterest-logo
telegram-logo discord-logo spotify-logo dribbble-logo behance-logo threads-logo snapchat-logo google-logo apple-logo
`.trim().split(/\s+/);

const root = process.argv[2];
if (!root) throw new Error('pass the path to @phosphor-icons/react');
const pascal = (s) => s.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const attr = (k) => k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());
const toSvg = (el) => {
	if (typeof el === 'string') return '';
	const kids = el.c.flat().map(toSvg).join('');
	if (el.t === 'F') return kids;
	const props = Object.entries(el.p || {}).map(([k, v]) => `${attr(k)}="${v}"`).join(' ');
	return `<${el.t}${props ? ' ' + props : ''}${kids ? `>${kids}</${el.t}>` : '/>'}`;
};
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'icons-'));
const out = {};
const missing = [];
for (const name of [...new Set(NAMES)]) {
	const file = path.join(root, 'dist/defs', pascal(name) + '.es.js');
	if (!fs.existsSync(file)) { missing.push(name); continue; }
	const src = fs.readFileSync(file, 'utf8').replace(/import \* as (\w+) from "react";/, (_, v) => 'const ' + v + ' = { createElement: (t, p, ...c) => ({ t, p, c }), Fragment: "F" };');
	const tmpFile = path.join(tmp, name + '.mjs');
	fs.writeFileSync(tmpFile, src);
	const map = (await import(tmpFile)).default;
	out[name] = toSvg(map.get('regular'));
}
if (Object.keys(out).length > 200) throw new Error('more than 200 icons');
const body = Object.keys(out).sort().map((k) => `\t'${k}': '${out[k]}',`).join('\n');
fs.writeFileSync('src/blocks/icon/icons.ts', `// Generated by scripts/icons.mjs from Phosphor Icons (regular weight, MIT,
// https://phosphoricons.com). 256 × 256 viewBox, drawn with currentColor.
export const ICONS: Record<string, string> = {\n${body}\n};\n\nexport const ICON_NAMES = Object.keys(ICONS).sort();\n`);
console.log(Object.keys(out).length, 'icons; missing:', missing.join(', ') || 'none');
